package com.philippe75.mastermind;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Scanner;

import org.apache.log4j.Logger;

import com.philippe75.game.Fish;
import com.philippe75.game.HowManyColors;
import com.philippe75.game.Main;
import com.philippe75.game.Mode;
import com.philippe75.game.PropertiesFile;
import com.philippe75.game.TextEnhencer;
import com.philippe75.generators.SecretColorCombinationGenerator;

/**
 * <b>DuelMastermind is a class that handle the Mastermind game in Duel Mode.</b>
 * <p>Steps of the game : 
 * <ul>
 * <li>A colour pool is created and the choices are displayed to the users.</li>
 * <li>User creates a colour combination, to be guessed by the computer, amongst those colours.</li>
 * <li>A random colour combination for user to be guessed is generated.</li>
 * <li>User tries a combination.</li>
 * <li>for each answer an hint is return. This hint indicates, how many colours are well placed and how many are present but not well placed in the combination.</li>
 * <li>Computer tries a combination.</li>
 * <li>An hint is also generated</li>
 * <li>Each turn, user and computer try a combination.</li>
 * <li>If user finds the secret combination first he wins, if computer finds first, user looses.</li>
 * </ul>
 * </p>
 * 
 * <p>
 * The random colour combination is generated via a SecretColoCombinationGenerator. 
 * </p>
 * 
 * <p>
 * The secret combination length and the pool of colours can be set in a DataConfig.properties file.
 * </p>
 * 
 * @see SecretColorCombinationGenerator
 * @see ChallengerMastermind#setProperties()
 * 
 * @author PPlaxine
 * @version 1.0
 */
public class DuelMastermind implements Mode{
	
	/**
	 * Secret colour combination generator. 
	 * 
	 * For more information about the generator, please see SecretColorCombinationGenerator class doc.  
	 * 
	 * @see SecretColorCombinationGenerator
	 * @see DuelMastermind#startTheGame()
	 */
	private SecretColorCombinationGenerator sCG;
	
	/**
	 * Pool of colours used for the game. 
	 * 
	 * @see DuelMastermind#printQuestion()
	 * @see DuelMastermind#compareAnswer()
	 */
	private Map<Integer, String> colorPool = new HashMap<>(); 
	
	/**
	 * Store combination generated by the SecretColorCombinationGenerator
	 * 
	 * @see SecretColorCombinationGenerator
	 * @see DuelMastermind#initGame()
	 * @see DuelMastermind#compareAnswer()
	 */
	private Map<Integer, String> tabColCombi = new HashMap<>(); 
	
	/**
	 *Users answer in Map format, used for comparison. 
	 *
	 * @see DuelMastermind#initGame()
	 * @see DuelMastermind#compareAnswer()
	 */
	private Map<Integer, String> tabUserAnswer = new HashMap<>();
	
	/**
	 * Used to compare User answer and the secret colour combination. 
	 * 
	 * @see DuelMastermind#compareAnswerUser()
	 */
	private Map<Integer, String> tabToCompare = new HashMap<>();
	
	/**
	 * Used to compare computers answer and the users secret colour combination. 
	 * 
	 * @see DuelMastermind#compareAnswerComputer()
	 */
	private Map<Integer, String> tabToCompare2 = new HashMap<>(); 
	
	/**
	 * Stores the computer answer in Map format for comparison. 
	 * 
	 * @see DuelMastermind#compareAnswerComputer()
	 * @see DMastermind#generateComputerAnswer()
	 */
	private Map<Integer, String> tabComputerAnswer = new HashMap<>();
	
	/**
	 * Stores user combination with colours as values in String format. 
	 * 
	 * Also used to compare and generates computer answer.   
	 * 
	 * @see DuelMastermind#requestUserSecretCombi()
	 * @see DuelMastermind#compareAnswerComputer()
	 * @see DefenderMastermind#generateComputerAnswer()
	 */
	private Map<Integer, String> userSelection;
	
	/**
	 * Pool containing all the possible colours.
	 * 
	 * @see DuelMastermind#initiateColorChoice()
	 * @see DuelMastermind#tabColorPool
	 */
	private List<String> tabColor;
	
	/**
	 * Pool of colours of the size defined by HowManyColors, for the player to choose from. 
	 * 
	 * @see DuelMastermind#initiateColorChoice()
	 * @see DuelMastermind#generateQuestion()
	 * @see DuelMastermind#requestUserSecretCombi()
	 * @see DuelMastermind#generateComputerAnswer()
	 */
	private List<String> tabColorPool;
	
	/**
	 * Store the colours present but not well placed, to be re-injected in the next computer answer. 
	 * 
	 * @see DuelMastermind#generateComputerAnswer()
	 * @see DuelMastermind#compareAnswerComputer()
	 */
	private List<String> tabColorToReinject = new ArrayList<>();
	
	/**
	 * combination length for the game. 
	 * 
	 * Defines the length of the secret combination to be generated
	 * It can be modified via the dataConfig.properties file 
	 * 
	 * @see DuelMastermind#setProperties()
	 * @see DuelMastermind#startTheGame()
	 */
	private int combiLength;
	
	/**
	 * Store the number of colours at the correct position for the user. 
	 * 
	 *  @see DuelMastermind#initGame()
	 *  @see DuelMastermind#compareAnswerUser()
	 */
	private int correctPositionUser;
	
	/**
	 * Store the number of colours at the correct position for the computer. 
	 * 
	 *  @see DuelMastermind#initGame()
	 *  @see DuelMastermind#compareAnswerComputer()
	 */
	private int correctPositionComputer; 
	
	/**
	 * Number of tries made.
	 * 
	 * @see DuelMastermind#getUserAnswer()
	 */
	private int tries = 0;
	
	/**
	 * User answer in String format with numerical value. 
	 * 
	 * @see DuelMastermind#initGame()
	 * @see DuelMastermind#getUserAnswer()
	 * @see DuelMastermind#compareAnswerUser()()
	 */
	private String userAnswer=""; 
	
	/**
	 * Stores user combination with colours as values in String format. 
	 * 
	 * Also used to compare and generates computer answer.   
	 * 
	 * @see DuelMastermind#requestUserSecretCombi()
	 * @see DuelMastermind#compareAnswerUser()
	 * @see DuelMastermind#generateComputerAnswer()
	 */
	private String userSecretCombination;
	
	/**
	 * Enumeration that define the size of the colour pool to request to SecretColorCombinationGenerator. 
	 * 
	 * @see SecretColorCombinationGenerator
	 * @see DuelMastermind#setProperties()
	 * @see DuelMastermind#startTheGame()
	 */
	private HowManyColors howManyColors;					
	Scanner clavier = new Scanner(System.in);
	
	/**
	 * Runs the game in developer mode if true is returned.
	 * 
	 * By default, if an argument -dev is passed when starting the program, the boolean will return the value true. 
	 * 
	 * Returns also true, if in dataProperties file the value of devMode is set to true;   
	 *  
	 * @see DuelMastermind#displaySecretNum()
	 * @see Main#isDev()
	 * @see Main#dev
	 * @see Main#main(String[])
	 * @see DuelMastermind#setProperties()
	 */
	private boolean dev = Main.isDev(); 
	
	/**
	 * Creates a logger to generate log of the class.	
	 */
	private static final Logger log = Logger.getLogger(DuelMastermind.class);
	
	/**
	 * Constructor of DuelMastermind.
	 * 
	 * When the class is instantiated, load properties to be used by the game.
	 * 
	 * @see DuelMastermind#setProperties()
	 * @see DuelMastermind#howManyColors
	 * @see DuelMastermind#combiLength
	 * @see DuelMastermind#dev
	 */
	public DuelMastermind() {
		if(setProperties())
			startTheGame();
	}
	
	/**
	 * Starts the game.  
	 * 
	 * A welcome screen is displayed.
	 * 
	 * Displays a request for user to make an entry. 
	 * 
	 * Initiate the game.
	 *  
	 * @see DuelMastermind#printWelcome()
	 * @see DuelMastermind#initiateColorChoice()
	 * @see DuelMastermind#generateQuestion()
	 * @see DuelMastermind#requestUserSecretCombi()
	 * @see DuelMastermind#displaySecretColorCombi()
	 * @see DuelMastermind#initGame()
	 */
	@Override
	public void startTheGame() {
		log.info("Start of Mastermind game in duel mode");
		if(dev)
			log.info("Game is running in developer mode");
		sCG = new SecretColorCombinationGenerator(combiLength, howManyColors);
		printWelcome();
		initiateColorChoice();
		generateQuestion();
		requestUserSecretCombi();
		displaySecretColorCombi();
		initGame();
		log.info("End of the game");
	}
	
	/**
	 * Returns true if the properties are set.
	 * 
	 * 	@see DefenderMastermind#howManyColors
	 *  @see DefenderMastermind#combiLength
	 *  @see DefenderMastermind#dev
	 * 	@see DefenderMastermind#startTheGame()
	 */
	@Override
	public boolean setProperties() {
		howManyColors = HowManyColors.valueOf((PropertiesFile.getPropertiesFile("ColorPool")));
		combiLength = Integer.parseInt(PropertiesFile.getPropertiesFile("CombinationLength"));
		if(new String("true").equals(PropertiesFile.getPropertiesFile("devMode"))) {
			this.dev = true;
		}	
		log.info("Properties have been sucessfully set");
		return true; 
	}
	
	/**
	 * Display the welcome screen.
	 * 
	 * @see DuelMastermind#startTheGame()
	 */
	@Override
	public void printWelcome() {
		String 	str = TextEnhencer.ANSI_YELLOW;
				str += "\n\n******************************************\n";
				str += "*******         WELCOME TO         *******\n";
				str += "*******      MASTERMIND GAME       *******\n";
				str += "*******         DUEL MODE          *******\n";	
				str += "******************************************";
				str += TextEnhencer.ANSI_RESET;
		System.out.println(str); 
	}
	
	/**
	 * Create a random pool of colour.
	 * 
	 *  @see DuelMastermind#tabColorPool
	 *  @see DuelMastermind#tabColor
	 *  @see DuelMastermind#howManyColors
	 */
	private void initiateColorChoice() {
		tabColorPool = new ArrayList<String>();
		tabColor = new ArrayList<String>();
		
		tabColor.add("Red");
		tabColor.add("Blue");
		tabColor.add("Green");
		tabColor.add("Yellow");
		tabColor.add("Orange");
		tabColor.add("Purple");
		tabColor.add("Brown");
		tabColor.add("Pink");
		tabColor.add("Gold");
		tabColor.add("Silver");
		
		Collections.shuffle(tabColor);
		
		tabColorPool.addAll(tabColor.subList(0, howManyColors.getIntValue()));	// à resoudre 
	
	}
	
	/**
	 * Creates the question to summit to the user.
	 * 
	 * @see DuelMastermind#tabColorPool
	 */
	private void generateQuestion() {
		int i = 0;
		String str =""; 
		for (String couleur : tabColorPool) {
			str += "["+ i +"]" + couleur +" ";
			i++;
		}
		
		System.out.println(TextEnhencer.ANSI_YELLOW + "\n" + str);
		System.out.println("\nPlease compose your secret color combination by choosing " + combiLength + " colors amongst the colors listed." + TextEnhencer.ANSI_RESET);
	}
	
	/**
	 *  Request the user to make a keyboard entry.
	 *  
	 *  also verify if the entry is correct.
	 *  
	 *  @see DuelMastermind#userAnswer
	 */
	private void requestUserSecretCombi() {
		
		userSelection = new HashMap<>(); 
		userSecretCombination = ""; 
		do {
			//Using Regex to make sure user enter the right value type (Integer), as well as,  the correct length of this value type, and not higher range of selection offers.   
			if(userAnswer !="") {
				if(!userAnswer.matches("^[./[0-9]]+$")) { 
					System.out.println(TextEnhencer.ANSI_RED + "Please enter a number instead of a characters." + TextEnhencer.ANSI_RESET);
					log.warn("User entry mismatch the type required");
				}else if (userAnswer.length() > combiLength || userAnswer.length() < combiLength){	
					System.out.println((userAnswer.length() > combiLength )? TextEnhencer.ANSI_RED + "The number of digits is superior to the number of digits required" + TextEnhencer.ANSI_RESET
							: TextEnhencer.ANSI_RED + "The number of digits is inferior to the number of digits required" + TextEnhencer.ANSI_RESET);
					log.warn("User entry mismatch the length of digits required");
				}else if (!userAnswer.matches("^[./[0-"+(tabColorPool.size() -1) +"]]+$")) { 
					System.out.printf(TextEnhencer.ANSI_RED + "Your selection has to be composed of number bewteen [0] and [%d]\n" + TextEnhencer.ANSI_RESET, (tabColorPool.size()-1));
					log.warn("User entry mismatch the possible answer choices");
				}
			}
			System.out.print(TextEnhencer.ANSI_YELLOW);
			this.userAnswer = clavier.nextLine();
			System.out.print(TextEnhencer.ANSI_RESET);
		} while ( userAnswer.length() > combiLength || userAnswer.length() < combiLength|| !userAnswer.matches("^[./[0-"+ (tabColorPool.size()-1)+"]]+$") || !userAnswer.matches("^[./[0-9]]+$") );
	
		// Convert String userAnswer digits into a Map userSelection with colours as value  
		for (int i = 0; i < userAnswer.length(); i++) {
			userSelection.put(i, tabColorPool.get(Character.getNumericValue(userAnswer.charAt(i))));
			
			userSecretCombination += "|" + userSelection.get(i) + "|";
		}
		//reset user Anwser 
		userAnswer = ""; 
		System.out.println(TextEnhencer.ANSI_YELLOW + "You have selected the folwing secret color combination : \n\t*** " + userSecretCombination + " ***\n" + TextEnhencer.ANSI_RESET);
	}
	
	/**
	 * Displays the secret combination if mode dev is activated
	 *  
	 * @see DuelMastermind#dev
	 * @see DuelMastermind#startTheGame()
	 */
	private void displaySecretColorCombi() {
		System.out.println(TextEnhencer.ANSI_CYAN + "Computer has generated a secret combination for you to guess ..." + TextEnhencer.ANSI_RESET);	
		if(dev)
			System.out.printf(TextEnhencer.ANSI_CYAN + "*** Secret Color Combination : %s ***\n\n" + TextEnhencer.ANSI_RESET, sCG.toString());
		System.out.println("");
	}
		
	/**
	 * Prints the Question with the random generated colours to choose from. 
	 * 
	 *  @see DuelMastermind#sCG
	 *  @see DuelMastermind#colorPool
	 */
	private void printQuestion() {	
		String str ="";
			 
		for (int i = 0; i < sCG.getColorPool().size(); i++) {
				
			str += " ["+ (i) +"]" + sCG.getColorPool().get(i);
				
			// add each colour of a secret combination to colorPool 
			colorPool.put(i, sCG.getColorPool().get(i)); 
		}
		//print the question containing the colorpool choices 
		System.out.printf(TextEnhencer.ANSI_YELLOW + "Please enter a combination of %d choices amongst those colors :%s.\n" + TextEnhencer.ANSI_RESET, combiLength , str);
	}
	
	/**
	 * Initiate the game. 
	 * 
	 * Get the user answer. 
	 * 
	 * Compare the user answer. 
	 * 
	 * Get the computer answer. 
	 * 
	 * Compare the computer answer. 
	 * 
	 * All those steps are repeated as long as the secret combination is not found. 
	 * 
	 * If user finds the secret combination first, he Wins. If computer finds the secret combination first, user looses.     
	 * 
	 * @see DuelMastermind#getUserAnswer()
	 * @see DuelMastermind#compareAnswerUser()
	 * @see DuelMastermind#generateComputerAnswer()
	 * @see DuelMastermind#compareAnswerComputer()
	 * @see Mode#displayFish()
	 */
	private void initGame() {
		// store the combination in tabColComni 
		tabColCombi = sCG.getTabColorCombination(); 
			
		do {		
				getUserAnswer();
				compareAnswerUser();
				if(correctPositionUser != this.combiLength) {
					generateComputerAnswer();
					compareAnswerComputer();
				}
				userAnswer = ""; 
				
			} while (correctPositionUser != this.combiLength && correctPositionComputer != this.combiLength );
		if(correctPositionComputer == this.combiLength) {
			System.out.printf(TextEnhencer.ANSI_RED +  "\n\t\t\t   .+*°*+..+> | GAME OVER !!! | <.+.+*°*+." + TextEnhencer.ANSI_CYAN + "\n\nComputer found your secret combination first !!! The secret combination was %s\n" + TextEnhencer.ANSI_RESET, sCG.toString());
			
		}else {
			Fish.displayFish();
			System.out.printf(TextEnhencer.ANSI_YELLOW + "\n\t.+*°*+.+> | Congratulations you WIN !!! | <+.+*°*+.\n\nYou have found the correct secret color combination first !!!" + TextEnhencer.ANSI_RESET);
		}
	}
	
	/**
	 *  Request the user to make a keyboard entry.
	 *  
	 *  also verify if the entry is correct.
	 *  
	 *  @see DuelMastermind#userAnswer
	 */
	private void getUserAnswer() {
		 tries++; 
		 tabUserAnswer.clear();
		// Repeat while user didn't enter the correct value 
		do {
			//Using Regex to make sure user enter the right value type (Integer) and the correct length of this value type  
			if(userAnswer !="") {
				if(!userAnswer.matches("^[./[0-9]]+$")) { 
					System.out.println(TextEnhencer.ANSI_RED + "Please enter a number instead of a characters." + TextEnhencer.ANSI_RESET);
					log.warn("User entry mismatch the type required");
				}else if (!userAnswer.matches("^[./[0-"+ (sCG.getColorPool().size()-1) + "]]+$")) { 
					System.out.printf(TextEnhencer.ANSI_RED + "You have to enter a number bewteen [0] and [%d]\n" + TextEnhencer.ANSI_RESET, sCG.getColorPool().size()-1);
					log.warn("User entry mismatch the possible answer choices");
				}else {	
					System.out.println((combiLength < userAnswer.length())? TextEnhencer.ANSI_RED + "The number of digits is superior to the number of digits required" + TextEnhencer.ANSI_RESET
							: TextEnhencer.ANSI_RED + "The number of digits is inferior to the number of digits required" + TextEnhencer.ANSI_RESET);
					log.warn("User entry mismatch the length of digits required");
				}
			}
			if(tries<2) {
				System.out.println(TextEnhencer.ANSI_YELLOW + "You are the first to play!" + TextEnhencer.ANSI_RESET);
			}else {
				System.out.println(TextEnhencer.ANSI_YELLOW + "It is your turn to play" + TextEnhencer.ANSI_RESET);
			}
			printQuestion();
			System.out.print(TextEnhencer.ANSI_YELLOW);
			// store the user answer in String but with numerical values
			this.userAnswer = clavier.nextLine();
			System.out.print(TextEnhencer.ANSI_RESET);
			
		} while (!userAnswer.matches("^[./[0-9]]+$") || combiLength != userAnswer.length() 
				|| !userAnswer.matches("^[./[0-"+(sCG.getColorPool().size()-1) +"]]+$") );		
	}
	
	/**
	 * Compare user answer with the secret colours combination. 
	 * 
	 * Indicates how many colours are well placed and how many are present but not well placed in the combination.
	 * 
	 * @see DuelMastermind#tabUserAnswer
	 * @see DuelMastermind#tabToCompare
	 */
	private void compareAnswerUser() {
		String str=""; 
		int index = 0;
		correctPositionUser = 0; 
		int exist = 0;
		tabToCompare.putAll(tabColCombi);
				
		for (int i = 0; i < userAnswer.length(); i++) {
			// userAnswer converted in int and stored in index 
			index = Character.getNumericValue((userAnswer.charAt(i)));
			// then converted in colour and stored in MAP 
			tabUserAnswer.put(i,(String)colorPool.get(index));
			// each element is also added to str for print
			str += "|" + tabUserAnswer.get(i) + "|"; 		
		}
	
		// check if any colour is at the same position in tabUserAnswer and tabToCompare 
		for (int i = 0; i < tabUserAnswer.size(); i++) {
			//if element at the correct position 
			if(tabUserAnswer.get(i).equals(tabToCompare.get(i))){
				//increase correctPosition 
				correctPositionUser++;
				// and replace the value in both tabs 
				tabToCompare.replace(i, "Found");
				tabUserAnswer.replace(i, "Found2"); 
			}
		}
	
		// amongst the remaining values check if there is any match 
		for (int i = 0; i < tabUserAnswer.size(); i++) {
			for (int j = 0; j < tabUserAnswer.size(); j++) {
				// if tabUserAnswer contains at any position an element contained in tabCompare
				if(tabUserAnswer.get(i).equals(tabToCompare.get(j))) {
					// replace the value in both tabs 
					tabToCompare.replace(j, "Found3");
					tabUserAnswer.replace(i, "Found4");
					//increase exist 
					exist++;
				}
			}	
		}
		System.out.printf(TextEnhencer.ANSI_GREEN + "Your anwser is %s ---> %d well placed, %d exist but not well placed.\n" + TextEnhencer.ANSI_RESET,str, correctPositionUser, exist);
	}
	
	/**
	 * Finds the correct way to handle the result and generate new answer based on the previous. 
	 * 
	 * @see DuelMastermind#tabComputerAnswer
	 * @see DuelMastermind#tabColorToReinject
	 */
	private void generateComputerAnswer() {
		
		Random random = new Random(); 
		int index = 0; 
		//First try 
		if(tabComputerAnswer.isEmpty()) {	
			for (int i = 0; i <userSelection.size(); i++) {
				index = random.nextInt(tabColorPool.size());
				tabComputerAnswer.put(i, tabColorPool.get(index));
			}
		// other tries	
		}else {
			for (int i = 0; i < tabComputerAnswer.size(); i++) {
				
				// if value of the element in tabComputerAnswer is "found" 
				if(tabComputerAnswer.get(i).equals("Found2")) {
					//replace "found" by the value of user selection 
					tabComputerAnswer.replace(i,userSelection.get(i));
					//remove the value from tabColorToReinject if the color is found 
					if(tabColorToReinject.contains(userSelection.get(i))) {		// ici 
						if(!tabColorToReinject.isEmpty()) {
							tabColorToReinject.remove(userSelection.get(i));
						}
					}
					
				// if value of element in tabComputerAnswer exist but not at the right place 	
				}else if(tabComputerAnswer.get(i).equals("Found4") && tabColorToReinject.size() > 0) {
					//select a random element amongst those that exist but not at the right place 
					int index2 = random.nextInt(tabColorToReinject.size()); // ICI !!!! 
					// put them in the next ComputerAnswer 
					tabComputerAnswer.replace(i,(tabColorToReinject.get(index2)));
					
					
				//if value does not exist replace by a random value 	
				}else {
						int index3 = random.nextInt(tabColorPool.size());  
						tabComputerAnswer.replace(i, tabColorPool.get(index3));
				}
			}
		}
	}
	
	/**
	 * Compare computer answer with the users secret colours combination. 
	 * 
	 * Indicates how many colours are well placed and how many are present but not well placed in the combination.
	 * 
	 * @see DuelMastermind#tabComputerAnswer
	 * @see DuelMastermind#userSelection
	 * @see DuelrMastermind#tabToCompare2
	 */
	private void compareAnswerComputer() {
		String str = ""; 
		
		for (int i = 0; i < tabComputerAnswer.size(); i++) {
			str += "|" + tabComputerAnswer.get(i) + "|";
		}
		
		correctPositionComputer = 0; 
		int exist = 0;
		tabToCompare2.putAll(userSelection);
				
		// check if any colour is at the same position in tabUserAnswer and tabToCompare 
		for (int i = 0; i < tabComputerAnswer.size(); i++) {
			//if element at the correct position 
			if(tabComputerAnswer.get(i).equals(tabToCompare2.get(i))){
				//increase correctPosition 
				correctPositionComputer++;
				// and replace the value in both tabs 
				tabToCompare2.replace(i, "Found");
				tabComputerAnswer.replace(i, "Found2"); 
			}
		}
	
		// amongst the remaining values check if there is any match 
		for (int i = 0; i < tabComputerAnswer.size(); i++) {
			for (int j = 0; j < tabComputerAnswer.size(); j++) {
				// if tabUserAnswer contains at any position an element contained in tabCompare
				if(tabComputerAnswer.get(i).equals(tabToCompare2.get(j))) {
					// replace the value in both tabs
					if(!tabColorToReinject.contains(tabComputerAnswer.get(i)))
						tabColorToReinject.add(tabComputerAnswer.get(i));
					tabToCompare2.replace(j, "Found3");
					tabComputerAnswer.replace(i, "Found4");
					//increase exist 
					exist++;
				}
			}	
		}
		System.out.println(TextEnhencer.ANSI_CYAN + "\nComputer has to find the following combination " + userSecretCombination);
		System.out.printf("Computer tries %s ---> %d well placed, %d exist but not well placed.\n\n" + TextEnhencer.ANSI_RESET,str, correctPositionComputer, exist);
	}
}
